language: python

python:
  - 3.6

services: postgresql

env:
  - DJANGO=2.0.6

before_install:
  - export DJANGO_SETTINGS_MODULE=deeplearning.settings
  - export PYTHONPATH=$HOME/builds/amulyareddy99/Eye2Brain/blob/master/Django%20app
  - export PIP_USE_MIRRORS=true
  - gem install bundler

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

# before_script:
#   - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - cd Django\ app
  - python manage.py --noinput

